  - name: firewall rules
    ufw: rule=allow proto=tcp direction=in port={{ item }}
    loop: ['6443', '2379:2380', '10252']

  - name: Check if Kubernetes has already been initialized.
    stat: path=/etc/kubernetes/admin.conf
    register: kubernetes_init_stat

  - name: Initialize Kubernetes cluster
    command: >
      kubeadm init
      --pod-network-cidr={{ kubernetes_pod_network }}
    when: not kubernetes_init_stat.stat.exists
    register: kube_gets_init

  - name: Check if kubernetes user .kube directory has already been created.
    stat: path=/home/kubernetes/.kube/config
    register: kubernetes_user_folder

  - name: Create .kube folder with config for kubernetes user.
    block:

      - name: Create .kube folder inside home.
        file: src=/home/kubernetes/.kube state=directory
      
      - name: Copy config file.
        copy: src=/etc/kubernetes/admin.conf dest=kubernetes/.kube/config remote_src=yes

      - name: Change permissions on folder.
        file: path=/home/kubernetes/.kube/config owner=kubernetes group=kubernetes

    when: kubernetes_user_folder.stat.exists